### ISSUE TITLE
Add installation instructions for different platforms

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/git-and-github-workshop-2020#1]
Make a new file - `installation.md`

For each of the following platforms
- Linux
- Windows
- OSX

For each platform
- Mention the commands or Mention a link of the article which can help in installing the simplest way
- At the end, mention a way to verify if installed or not: `git --version`
- Add instructions to make a Github account preferably add a video

**Ensure to add the latest instructions**

**Comment by Holmes7** [comment]
I don't think we need to add it for OS X git comes pre-installed in Mac

**Comment by rakaar** [comment]
>I don't think we need to add it for OS X git comes pre-installed in Mac

thanks, didn't knew about this.
Is it only new version, or also available in old versions?

if not available in old version then lets add it

**Comment by Holmes7** [comment]
Looks like it is available only after version 10.9
This is where we can install the binary https://sourceforge.net/projects/git-osx-installer/
Also I found this article nice https://www.atlassian.com/git/tutorials/install-git
Amrta this should help you for OS X part

**Comment by amrtachaurasia** [comment]
@rakaar i have created a pull request, please do review it and let me know if something needs to be added or modified
